### ISSUE TITLE
BUG: Conflict in Torch libraries affecting multiprocessing

### ISSUE THREAD

**Issue by nadul99** [LopezGroup-ICIQ/care#11]
I tried running it by typing the following, but it doesn't work.

care_run -i ./src/care/scripts/example_c1o2.toml -o output-sample

             _____                    _____                    _____                    _____
             /\    \                  /\    \                  /\    \                  /\    \
            /::\    \                /::\    \                /::\    \                /::\    \
           /::::\    \              /::::\    \              /::::\    \              /::::\    \
          /::::::\    \            /::::::\    \            /::::::\    \            /::::::\    \
         /:::/\:::\    \          /:::/\:::\    \          /:::/\:::\    \          /:::/\:::\    \
        /:::/  \:::\    \        /:::/__\:::\    \        /:::/__\:::\    \        /:::/__\:::\    \
       /:::/    \:::\    \      /::::\   \:::\    \      /::::\   \:::\    \      /::::\   \:::\    \
      /:::/    / \:::\    \    /::::::\   \:::\    \    /::::::\   \:::\    \    /::::::\   \:::\    \
     /:::/    /   \:::\    \  /:::/\:::\   \:::\    \  /:::/\:::\   \:::\____\  /:::/\:::\   \:::\    \
    /:::/____/     \:::\____\/:::/  \:::\   \:::\____\/:::/  \:::\   \:::|    |/:::/__\:::\   \:::\____\
    \:::\    \      \::/    /\::/    \:::\  /:::/    /\::/   |::::\  /:::|____|\:::\   \:::\   \::/    /
     \:::\    \      \/____/  \/____/ \:::\/:::/    /  \/____|:::::\/:::/    /  \:::\   \:::\   \/____/
      \:::\    \                       \::::::/    /         |:::::::::/    /    \:::\   \:::\    \
       \:::\    \                       \::::/    /          |::|\::::/    /      \:::\   \:::\____\
        \:::\    \                      /:::/    /           |::| \::/____/        \:::\   \::/    /
         \:::\    \                    /:::/    /            |::|   |               \:::\   \/____/
          \:::\    \                  /:::/    /             |::|   |                \:::\    \
           \:::\____\                /:::/    /              \::|   |                 \:::\____\
            \::/    /                \::/    /                \:|   |                  \::/    /
             \/____/                  \/____/                  \|___|                   \/____/

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━ Generating the C1O2 CRN blueprint  ━━━━━━━━━━━━━━━━━━━━━━━━━━━┓

Generating Chemical Space...           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Generating extended Chemical Space...  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing Intermediate objects...     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Processing ElementaryReactions...      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Generating adsorption reactions...     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Generating rearrangement reactions...  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00

+-------------------------------------+-----------------+----------+
|               Category              | Number of Items | Time (s) |
+-------------------------------------+-----------------+----------+
|         Saturated molecules         |        6        |   0.02   |
| Fragments and unsaturated molecules |        32       |   0.45   |
+-------------------------------------+-----------------+----------+
|        Dissociation reactions       |        50       |          |
|         Adsorption reactions        |        12       |   0.47   |
|       Rearrangement reactions       |        7        |   0.20   |
|                                     |                 |          |
+-------------------------------------+-----------------+----------+
|       Total number of species       |        38       |   0.47   |
|      Total number of reactions      |        69       |   1.12   |
+-------------------------------------+-----------------+----------+

┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ CRN blueprint generated ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

┏━━━━━━━━━━━━ Evaluating the C1O2 CRN on Ru(10m11) ━━━━━━━━━━━┓

 Energy estimation of the intermediates...
 Intermediates energy calculator:  GAME-Net-UQ (557K params, device=cpu)
 Processing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--

It is displayed as above and stops at 0% and does not operate.

**Comment by pol-sb** [comment]
Hey @nadul99, thank you very much for your feedback.

We found some issues with multiprocessing when using the default installation settings. We updated the installation procedure in [README.md](https://github.com/LopezGroup-ICIQ/care/blob/main/README.md) and libraries, could you try the new approach and let us know if it works for you?

Thank you again!
@oliverlovros, @SantiagoMorandi and @pol-sb

**Comment by nadul99** [comment]
Thank you for updating the code.
